### ISSUE TITLE
你这个是针对哪个版本的quick的？

### ISSUE THREAD

**Issue by uhoohei** [yszheda/quickx-extensions#1]
还有就是为何不给quick添加一个patch呢？

**Comment by yszheda** [comment]
Hi uhoohei！
- 针对哪个版本的quick的？
  quick v3.3
- 为何不给quick添加一个patch？
  这个repo主要为解决一些实际问题所做的更改，偏workaround性质。由于动到了quick的一些内部实现逻辑，在尚不清楚是否会造成其他影响或是否有更好的改法前还是暂时不向quick提交patch。

**Comment by uhoohei** [comment]
我看了一下其实动的也不算大，你提个patch给quick，他们也会审核的吧？

**Comment by uhoohei** [comment]
然后我对比了一下代码，你是用的3.3final吗？GIT里面的V3分支的与你的base代码有所不同了

**Comment by yszheda** [comment]
> 然后我对比了一下代码，你是用的3.3final吗？GIT里面的V3分支的与你的base代码有所不同了

这是因为我一开始提交的就是改过的代码，如果您只想看diff的话可以参考：
http://galoisplusplus.gitcafe.io/blog/2015/07/06/patch-for-quickx-button/

> 我看了一下其实动的也不算大，你提个patch给quick，他们也会审核的吧？

quickx目前的UIButton实现是只`addChild`当前按钮状态的sprite，我改成了一开始便把所有状态的sprite都`addChild`进来。一是尚不清楚原来实现者这么设计的意图，二是我主要按照自己项目的实际需要去改的，可能没兼顾到所有的API，虽然用quickx的sample测过没问题，但不能保证完全没问题XD
所以我想目前我这个简单粗暴的改法可能还不是一个好的fix，如果我想到不用改动原来设计的改法会向quickx提PR的，如果您有好的解决方案也可以直接向quickx提。
